- name: Downloading the repo file for Jenkins.
  shell: 
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  become: yes

- name: Installing jenkins
  yum: {{item}}
  with_items:
    - epel-release
    - java-11-openjdk-devel
    - jenkins
  state: present
  become: yes