- name: Installing NGINX
  yum: 
   name: nginx
   state: present

- name: Starting nginx
  systemd:
   name: nginx
   state: started
   enabled: true
 
- name: deleting old contect
  file:
    path: /usr/share/nginx/html
    state: absent
  become: yes

- name: creating path
  file:
    path: /usr/share/nginx/html
    state: directory
  become: yes

- name: Downlaoding {{COMPONENT}} zip file
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/centos/{{COMPONENT}}/
    remote_src: yes
    owner: centos
    group: centos

- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: "/usr/share/nginx/html"
    remote_src: yes
  become: yes

- name: Starting Nginx
  systemd:
    name: nginx
    state: restarted
  ignore_errors : yes
