- name: Installing httpd
  yum: 
   name: 
    - httpd
   state: present
  become: true
 
- name: deleting old contect
  file:
    path: /usr/share/httpd/
    state: absent
  become: yes

- name: creating path
  file:
    path: /usr/share/httpd/html
    state: directory
  become: yes

- name: Downlaoding {{COMPONENT}} zip file
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/centos/{{COMPONENT}}/
    remote_src: yes
    owner: centos
    group: centos

- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: "/usr/share/httpd/html"
    remote_src: yes
  become: yes

- name: restarting httpd
  service:
    name: httpd
    state: started
  ignore_errors : yes
  become: yes